### ISSUE TITLE
Définir les éléments principaux du projet

### ISSUE THREAD

**Issue by cdlm** [TL1-fa17/projet3#1]
Faites un cahier des charges rapide dans le fichier README:
- une idée du type de jeu
- les éléments principaux (avatar, obstacles, niveaux…)
- les interactions entre ces éléments

**Comment by jeancastel** [comment]
Fait dans le README

**Comment by Adelomelle** [comment]
j'ai rédigé une ébauche dans le README,
reste quelques questions auxquelles nous répondrons durant le télégroupe,
et quelques améliorations...

**Comment by cdlm** [comment]
Projet terminé
