### ISSUE TITLE
Nom et port du serveur ne devraient pas être en dur

### ISSUE THREAD

**Issue by cdlm** [TL1-fa17/projet3#4]
Vous pouvez les passer en argument du programme principal du jeu (donc de `WindowsGame.main(…)`).
- dans Eclipse il faudra faire une configuration de lancement spécifique pour tester sur un serveur précis
- vous pouvez regarder si les arguments sont présents, et le cas échéant retomber sur une valeur en dur, mais je recommanderais de prendre localhost plutôt qu'un serveur externe, pour pouvoir tester sans dépendre d'une connection réseau

**Comment by jeancastel** [comment]
Je suis en phase de test pour la communication par socket, j'ai mis ces valeurs en dur pour tester si la communication fonctionnait par le net.

En effet, à terme, le joueur choisira le serveur qu'il veut rejoinde lors du lancement du client.

**Comment by cdlm** [comment]
Projet terminé
